import { memo } from 'react';
import type { InverterSnapshot } from '../lib/types';
import { formatEnergy } from '../lib/format';

interface Props {
  snapshot: InverterSnapshot;
}

interface TileDef {
  label: string;
  value: string;
  accent: string;
  icon: string;
  /** Short tooltip explaining what this tile includes / excludes. */
  tooltip: string;
}

function SummaryTilesInner({ snapshot: s }: Props) {
  // The "Today" tiles expose the four streams that participate in the
  // home-level energy balance:
  //
  //   solar + import = export + home_use + battery_charged − battery_discharged
  //
  // Displaying both `home_use` (load) and the two battery terms lets the
  // user audit that the numbers add up. Previously only "Consumption" was
  // shown, which obscured where battery charging goes in the equation.
  //
  // Each tile carries a tooltip explaining what it includes and how it
  // fits into the balance, so users can reconcile the numbers without
  // having to read the source code.
  const tiles: TileDef[] = [
    {
      label: 'Solar Today',
      value: formatEnergy(s.today_solar_kwh),
      accent: '#F59E0B',
      icon: '☀️',
      tooltip:
        'Total energy generated by the solar panels since midnight. ' +
        'Includes everything the panels produced — whether it went to the ' +
        'home, into the battery, or was exported to the grid.',
    },
    {
      label: 'Home Use',
      value: formatEnergy(s.home_energy_today_kwh),
      accent: '#14B8A6',
      icon: '🏠',
      tooltip:
        'Energy consumed by your home appliances since midnight. ' +
        'Excludes energy stored in the battery — battery charging is ' +
        'shown separately in "Battery Charged".',
    },
    {
      label: 'Battery Charged',
      value: formatEnergy(s.today_charge_kwh),
      accent: '#A78BFA',
      icon: '🔌',
      tooltip:
        'Total energy that flowed INTO the battery since midnight, from ' +
        'both solar and grid combined. (The grid-only portion is the ' +
        'AC-charge figure used internally for the consumption formula.)',
    },
    {
      label: 'Import',
      value: formatEnergy(s.today_import_kwh),
      accent: '#EF4444',
      icon: '⬇️',
      tooltip:
        'Total energy drawn from the grid since midnight. Includes both ' +
        'grid-to-home and grid-to-battery (AC charge).',
    },
    {
      label: 'Export',
      value: formatEnergy(s.today_export_kwh),
      accent: '#22C55E',
      icon: '⬆️',
      tooltip:
        'Total energy exported to the grid since midnight. Comes from ' +
        'surplus solar and/or battery discharge when export is enabled.',
    },
    {
      label: 'Battery Discharged',
      value: formatEnergy(s.today_discharge_kwh),
      accent: '#22C55E',
      icon: '🔋',
      tooltip:
        'Total energy that flowed OUT of the battery since midnight — to ' +
        'both the home and the grid (if export is enabled).',
    },
  ];

  return (
    <div className="bg-bg-surface rounded-2xl p-6 h-full flex flex-col gap-4">
      <h2 className="hidden md:block text-text-primary text-base font-semibold tracking-wide">Today</h2>
      <div
        data-testid="summary-tiles-grid"
        className="gap-2 md:gap-3"
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
          gridAutoFlow: 'row',
        }}
      >
        {tiles.map((t) => (
          <div
            key={t.label}
            title={t.tooltip}
            className="min-w-0 bg-bg-elevated rounded-xl p-1.5 md:p-4 flex flex-col gap-1 md:gap-2 border border-transparent hover:border-white/5 transition-colors cursor-help"
          >
            <div className="flex items-center gap-1 md:gap-2">
              <span
                className="w-5 h-5 md:w-8 md:h-8 rounded-md md:rounded-lg flex items-center justify-center text-[10px] md:text-sm"
                style={{ backgroundColor: t.accent + '20' }}
              >
                {t.icon}
              </span>
              <span className="min-w-0 text-text-secondary text-[10px] md:text-xs font-medium leading-tight">{t.label}</span>
            </div>
            <span
              className="text-base md:text-xl font-mono font-bold tracking-tight"
              style={{ color: t.accent }}
            >
              {t.value}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

const SummaryTiles = memo(SummaryTilesInner);
export default SummaryTiles;
