#!/bin/bash
# Tests for scripts/check-tauri-plugin-versions.sh
#
# The guard's contract: given a checkout root, exit 0 iff every
# installed @tauri-apps/plugin-* package shares a major/minor release
# with the tauri-plugin-* crate cargo compiles; otherwise exit 1 and
# name both sides. tauri-cli hard-fails `tauri build` when they drift,
# which is what killed every platform job of the v0.85.0 release
# (run 37033633298) after Dependabot bumped the crates alone.
#
# Fixtures are staged temp trees so the two parsers (package-lock.json
# JSON, Cargo.lock [[package]] blocks) stay pinned against a future
# edit. The final test runs the guard against the real checkout.
#
# Run standalone: `bash tests/scripts/check-tauri-plugin-versions.test.sh`
# Or via `npm test` (wired through package.json).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CHECK="$REPO_ROOT/scripts/check-tauri-plugin-versions.sh"

if [ ! -x "$CHECK" ]; then
  echo "FAIL: checker not found or not executable at $CHECK" >&2
  exit 1
fi

# --- Test harness -------------------------------------------------------------

PASS=0
FAIL=0

assert_eq() {
  local label="$1" expected="$2" actual="$3"
  if [ "$expected" = "$actual" ]; then
    echo "  PASS  $label"
    PASS=$((PASS + 1))
  else
    echo "  FAIL  $label"
    echo "        expected: $expected"
    echo "        actual:   $actual"
    FAIL=$((FAIL + 1))
  fi
}

assert_contains() {
  local label="$1" needle="$2" haystack="$3"
  if [[ "$haystack" == *"$needle"* ]]; then
    echo "  PASS  $label"
    PASS=$((PASS + 1))
  else
    echo "  FAIL  $label"
    echo "        missing: $needle"
    echo "        in:      $haystack"
    FAIL=$((FAIL + 1))
  fi
}

assert_not_contains() {
  local label="$1" needle="$2" haystack="$3"
  if [[ "$haystack" != *"$needle"* ]]; then
    echo "  PASS  $label"
    PASS=$((PASS + 1))
  else
    echo "  FAIL  $label"
    echo "        unexpected: $needle"
    FAIL=$((FAIL + 1))
  fi
}

TMP_ROOT="$(mktemp -d)"
trap 'rm -rf "$TMP_ROOT"' EXIT

# Build a fake checkout at $root.
#   $2 js    — space-separated "name:version" npm plugin pairs, e.g.
#              "opener:2.6.0 autostart:2.6.0". Empty = no JS plugins.
#   $3 cargo — space-separated "name:version" crate pairs (without the
#              tauri-plugin- prefix). Empty = no plugin crates.
write_tree() {
  local root="$1" js="$2" cargo="$3"
  mkdir -p "$root/src-tauri"

  local js_entries="" entry name version
  for entry in $js; do
    name="${entry%%:*}"
    version="${entry##*:}"
    js_entries="${js_entries}${js_entries:+,}
    \"node_modules/@tauri-apps/plugin-${name}\": { \"version\": \"${version}\", \"resolved\": \"https://registry.npmjs.org/x\" }"
  done
  {
    echo '{'
    echo '  "name": "stub",'
    echo '  "lockfileVersion": 3,'
    echo '  "packages": {'
    printf '    "": { "name": "stub", "version": "1.0.0" }'
    if [ -n "$js_entries" ]; then
      printf ',\n%s\n' "$js_entries"
    else
      printf '\n'
    fi
    echo '  }'
    echo '}'
  } > "$root/package-lock.json"

  {
    echo '# This file is automatically @generated by Cargo.'
    echo '# It is not intended for manual editing.'
    echo 'version = 4'
    echo
    echo '[[package]]'
    echo 'name = "givenergy-local"'
    echo 'version = "0.85.0"'
    # A dependency with a shared prefix must not be mistaken for a plugin
    # crate, and `version` lines from other packages must not leak across
    # [[package]] blocks.
    echo
    echo '[[package]]'
    echo 'name = "tauri-plugin-not-installed"'
    echo 'version = "9.9.9"'
    for entry in $cargo; do
      name="${entry%%:*}"
      version="${entry##*:}"
      echo
      echo '[[package]]'
      echo "name = \"tauri-plugin-${name}\""
      echo "version = \"${version}\""
    done
  } > "$root/src-tauri/Cargo.lock"
}

# Run the guard against $1, capturing combined output and exit status.
RC=0
OUT=""
run_check() {
  set +e
  OUT="$(ROOT="$1" bash "$CHECK" 2>&1)"
  RC=$?
  set -e
}

# --- Tests --------------------------------------------------------------------

echo "tests/scripts/check-tauri-plugin-versions.test.sh"

# Test 1: JS package and crate on the same release → exit 0.
echo
echo "1. matching releases pass"
write_tree "$TMP_ROOT/match" "opener:2.6.0 autostart:2.6.0" "opener:2.6.0 autostart:2.6.0"
run_check "$TMP_ROOT/match"
assert_eq "matching major/minor exits 0" "0" "$RC"
assert_contains "reports the synced pair" "tauri-plugin-opener" "$OUT"
assert_contains "reports the synced npm package" "@tauri-apps/plugin-opener" "$OUT"
assert_not_contains "does not mistake an unrelated crate for a plugin" "9.9.9" "$OUT"

# Test 2: patch drift within the same minor is allowed — tauri-cli only
# compares major/minor, so the guard must not be stricter than the build.
echo
echo "2. patch-level drift still passes"
write_tree "$TMP_ROOT/patch" "opener:2.6.1" "opener:2.6.0"
run_check "$TMP_ROOT/patch"
assert_eq "applying npm patches without a crate bump exits 0" "0" "$RC"

# Test 3: the v0.85.0 failure — npm lags the crate by a minor.
echo
echo "3. minor drift fails and names both sides"
write_tree "$TMP_ROOT/minor" "opener:2.5.4" "opener:2.6.0"
run_check "$TMP_ROOT/minor"
assert_eq "npm lagging the crate exits 1" "1" "$RC"
assert_contains "names the npm version" "2.5.4" "$OUT"
assert_contains "names the crate version" "2.6.0" "$OUT"
assert_contains "names both packages" "@tauri-apps/plugin-opener" "$OUT"
assert_contains "names the crate" "tauri-plugin-opener" "$OUT"
assert_contains "explains that tauri build refuses the drift" "tauri build" "$OUT"

# Test 4: a major drift is equally fatal.
echo
echo "4. major drift fails"
write_tree "$TMP_ROOT/major" "autostart:3.0.0" "autostart:2.6.0"
run_check "$TMP_ROOT/major"
assert_eq "npm ahead by a major exits 1" "1" "$RC"
assert_contains "names the crate for the drifting plugin" "tauri-plugin-autostart" "$OUT"

# Test 5: only the drifting pair is reported.
echo
echo "5. one drifting pair among several fails"
write_tree "$TMP_ROOT/mixed" "opener:2.6.0 autostart:2.5.1" "opener:2.6.0 autostart:2.6.0"
run_check "$TMP_ROOT/mixed"
assert_eq "a single drifting pair exits 1" "1" "$RC"
assert_contains "names the drifting crate" "tauri-plugin-autostart" "$OUT"
assert_not_contains "does not blame the synced pair" "tauri-plugin-opener" "$OUT"

# Test 6: a JS plugin with no Rust crate behind it is a bug, not a pass.
echo
echo "6. a JS plugin without its crate fails"
write_tree "$TMP_ROOT/crate-missing" "opener:2.6.0" ""
run_check "$TMP_ROOT/crate-missing"
assert_eq "missing crate exits 1" "1" "$RC"
assert_contains "points at Cargo.lock" "Cargo.lock" "$OUT"
assert_contains "names the orphaned JS package" "@tauri-apps/plugin-opener" "$OUT"

# Test 7: Rust-only plugins (tauri-plugin-log) have no npm counterpart
# and must not be reported.
echo
echo "7. Rust-only plugins are ignored"
write_tree "$TMP_ROOT/rust-only" "opener:2.6.0" "opener:2.6.0 log:2.10.0"
run_check "$TMP_ROOT/rust-only"
assert_eq "a crate with no npm package exits 0" "0" "$RC"
assert_not_contains "does not report the Rust-only plugin" "tauri-plugin-log" "$OUT"

# Test 8: nothing to compare is not a failure.
echo
echo "8. a frontend with no Tauri plugins passes"
write_tree "$TMP_ROOT/none" "" "log:2.10.0"
run_check "$TMP_ROOT/none"
assert_eq "no JS plugins exits 0" "0" "$RC"
assert_contains "says why there was nothing to compare" "no @tauri-apps/plugin-" "$OUT"

# Test 9: a missing lockfile is a setup error, not a silent pass.
echo
echo "9. a missing package-lock.json fails loudly"
mkdir -p "$TMP_ROOT/no-lock/src-tauri"
cp "$TMP_ROOT/match/src-tauri/Cargo.lock" "$TMP_ROOT/no-lock/src-tauri/Cargo.lock"
run_check "$TMP_ROOT/no-lock"
assert_eq "missing package-lock exits 1" "1" "$RC"
assert_contains "names the missing file" "package-lock.json" "$OUT"

# Test 10: the real checkout must satisfy its own guard. This is the
# assertion that would have failed on the v0.85.0 tree (crates 2.6.0,
# npm 2.5.x) before the dependency bump.
echo
echo "10. the real checkout is in sync"
run_check "$REPO_ROOT"
assert_eq "real repo exits 0" "0" "$RC"

echo
echo "---------------------------------------"
echo "Passed: $PASS    Failed: $FAIL"
echo "---------------------------------------"
[ "$FAIL" -eq 0 ]
